# Generated by Django 4.2.3 on 2023-07-10 15:28

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPostuler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('number', models.PositiveIntegerField(blank=True, max_length=12)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('ville', models.CharField(blank=True, max_length=50)),
                ('pays', django_countries.fields.CountryField(max_length=2)),
                ('birthCertificate', models.FileField(blank=True, upload_to='media/document')),
                ('identityDocument', models.FileField(blank=True, upload_to='media/document')),
                ('recentCertificate', models.FileField(blank=True, upload_to='media/document')),
                ('signedEngagement', models.FileField(blank=True, upload_to='media/document')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'DocumentPostuler',
                'verbose_name_plural': 'DocumentPostulers',
            },
        ),
    ]
